# ------------------------------
# World and timing
# ------------------------------
WORLD_WIDTH_METERS = 40
WORLD_HEIGHT_METERS = 40
TIME_STEP = 0.05
RANDOM_SEED = 124

# ------------------------------
# Robot sensing and control
# ------------------------------
FOV_ANGLE = 120
VIEW_DISTANCE = 8
VISION_RAY_COUNT = 12
SHOW_VISION_RAYS = True
OBSTACLE_AVOID_DISTANCE = 1.5
OBSTACLE_TURN_GAIN = 1.8

# ------------------------------
# Planner and path display
# ------------------------------
A_STAR_GRID_RESOLUTION = 1.0
A_STAR_REPLAN_SECONDS = 1.2
A_STAR_GOAL_TOLERANCE = 0.65
A_STAR_LOOKAHEAD_STEPS = 1
A_STAR_INFLATION_MARGIN = 1.20
KNOWN_MAP_REPLAN_ON_NEW_OBS = True
PATH_LINE_WIDTH = 2.8
TARGET_MARKER_SIZE = 15
SUBGOAL_MARKER_SIZE = 9

# Optional local A* debug overlay.
SHOW_ASTAR_LOCAL_GRID = False
A_STAR_GRID_WINDOW_CELLS = 4
A_STAR_GRID_LINE_ALPHA = 0.14
A_STAR_GRID_OCC_ALPHA = 0.18
A_STAR_GRID_PATH_ALPHA = 0.20
A_STAR_GRID_UPDATE_FRAMES = 4
A_STAR_GRID_MAX_DRONES = 1

# Vision-ray styling.
RAY_LINE_WIDTH = 1.3
RAY_ALPHA = 0.55

# ------------------------------
# State estimation
# ------------------------------
PREDICTION_NOISE = [0.02, 0.07, 0.5]
MEASUREMENT_NOISE = [0.12, 2.5]
MEASUREMENT_ALPHA = 0.35

# ------------------------------
# Recovery / anti-stuck behavior
# ------------------------------
STUCK_WINDOW_SECONDS = 2.0
STUCK_PROGRESS_EPS = 0.8
STUCK_RECOVERY_SECONDS = 1.3
STUCK_REVERSE_SPEED = 0.45
STUCK_TURN_SPEED = 2.8

# ------------------------------
# Multi-robot setup
# ------------------------------
ROBOT_COUNT = 4
DRONE_NAME_PREFIX = "Drone"
DRONE_NAMES = [f"{DRONE_NAME_PREFIX} {i + 1}" for i in range(ROBOT_COUNT)]
DRONE_START_POSE = (WORLD_WIDTH_METERS / 2.0, 5.0, 90.0)
DRONE_START_SPACING = 1.6
START_SIMULATION_RUNNING = False
OUTPUT_ROOT_DIR = "outputs"

# ------------------------------
# Automatic exploration / partition
# ------------------------------
DEFAULT_MISSION_MODE = 'manual_click'   # 'manual_click' or 'auto_explore'
SHOW_PARTITION_OVERLAY_BY_DEFAULT = True
AUTO_EXPLORE_REPLAN_SECONDS = 1.0
AUTO_FRONTIER_MIN_COMPONENT_CELLS = 2
AUTO_PARTITION_EPSILON_METERS = 0.45
AUTO_GLOBAL_FRONTIER_FALLBACK = True
AUTO_FRONTIER_TOP_K_CANDIDATES = 8
AUTO_FRONTIER_INFO_GAIN = 1.15
AUTO_FRONTIER_PARTITION_PENALTY = 7.5
AUTO_FRONTIER_TEAMMATE_RADIUS = 4.0
AUTO_FRONTIER_TEAMMATE_PENALTY = 2.75
AUTO_FRONTIER_PROGRESS_WEIGHT = 0.55
AUTO_FRONTIER_MIN_GOAL_DISTANCE = 1.05
AUTO_LAUNCH_DISPERSAL_ENABLED = True
AUTO_LAUNCH_DISPERSAL_DISTANCE = 5.6
AUTO_LAUNCH_DISPERSAL_GOAL_TOLERANCE = 0.95
AUTO_LAUNCH_DISPERSAL_MAX_SECONDS = 9.0
AUTO_STOP_WHEN_FINISHED = True
AUTO_FINISH_HOLD_SECONDS = 1.0

SHOW_DENSITY_OVERLAY_BY_DEFAULT = False
AUTO_DENSITY_FRONTIER_WEIGHT = 2.25
AUTO_DENSITY_UNKNOWN_WEIGHT = 0.95
AUTO_DENSITY_FREE_WEIGHT = 0.08
AUTO_DENSITY_SMOOTHING_PASSES = 2
AUTO_FRONTIER_CENTROID_WEIGHT = 0.32
AUTO_FRONTIER_DENSITY_VALUE_WEIGHT = 0.85
DEFAULT_AUTO_POLICY = 'weighted_coverage'  # 'frontier' or 'weighted_coverage'
AUTO_COVERAGE_FALLBACK_GLOBAL = True
AUTO_COVERAGE_TOP_K_CANDIDATES = 14
AUTO_COVERAGE_DENSITY_GAIN = 2.25
AUTO_COVERAGE_CENTROID_PULL = 0.75
AUTO_COVERAGE_ROBOT_DISTANCE_WEIGHT = 0.18
AUTO_COVERAGE_TEAMMATE_RADIUS = 4.5
AUTO_COVERAGE_TEAMMATE_PENALTY = 3.2
AUTO_COVERAGE_PROGRESS_WEIGHT = 0.45
AUTO_COVERAGE_FRONTIER_BONUS = 1.25

# ------------------------------
# Random environment generation
# ------------------------------
OBSTACLE_COUNT = 9
OBSTACLE_SIZE_RANGE = (3.0, 5.0)
OBSTACLE_CLEARANCE = 2.0

LANDMARK_COUNT = 15
LANDMARK_SIZE = 0.8
LANDMARK_CLEARANCE = 1.3

START_CLEAR_RADIUS = 5.5
BOUNDARY_MARGIN = 3.0



# Mapping refinement: if a closed obstacle outline is observed,
# fill its enclosed interior as occupied so obstacles become solid.
FILL_ENCLOSED_OBSTACLE_INTERIORS = True
ENCLOSED_FILL_MAX_CELLS = 160
ENCLOSED_FILL_MIN_CELLS = 3
ENCLOSED_FILL_SEAL_ONE_CELL_GAPS = True

# Colors shared by multiple modules.
COLOR_UNKNOWN = '#d9dde3'
COLOR_FREE = '#f8fbff'
COLOR_OCCUPIED = '#5b6470'
COLOR_OBSTACLE = '#5A5A5A'
COLOR_BOUNDARY = 'red'
